[project]
name = "cube_dbt"
version = "0.1.0"
description = "dbt integration for Cube"
authors = [
    { name = "Artyom Keydunov", email = "artyom@cube.dev" },
    { name = "Igor Lukanin", email = "igor@cube.dev" },
]
dependencies = ["PyYAML>=6.0.1"]
requires-python = ">=3.10,<3.12"
readme = "README.md"
license = { text = "MIT" }

[dependency-groups]
dev = ["pytest", "ruff"]

[build-system]
requires = ["uv_build>=0.8.19,<0.9.0"]
build-backend = "uv_build"
